FORMAT: 1A

# BreadBakery

BreadBakery is a api to keep track of stock and goods that can be bought
at Bread's only Bakery in London.

## Questions Collection [/stock]

### List All Stock [GET]


+ Response 200 (application/json)

        + Headers
        connection: close
        content-type: application/json;charset=UTF-8
        date: Thu, 04 Oct 2018 22:06:09 GMT
   
    + Body


            [
            {
                "quantity": 20,
                "item": {
                    "name": "Bread",
                    "price": 1.2,
                    "id": "ecf41802-c810-11e8-a8d5-f2801f1b9fd1"
                }
            },
            {
                "quantity": 5,
                "item": {
                    "name": "Bun",
                    "price": 2.5,
                    "id": "ecf41fd2-c810-11e8-a8d5-f2801f1b9fd1"
                }
            },
            {
                "quantity": 12,
                "item": {
                    "name": "Baguette",
                    "price": 4.5,
                    "id": "ecf41e74-c810-11e8-a8d5-f2801f1b9fd1"
                }
            },
            {
                "quantity": 42,
                "item": {
                    "name": "Panini",
                    "price": 1.99,
                    "id": "ecf41aaa-c810-11e8-a8d5-f2801f1b9fd1"
                }
            },
            {
                "quantity": 23,
                "item": {
                    "name": "Pie",
                    "price": 6.5,
                    "id": "ecf420fe-c810-11e8-a8d5-f2801f1b9fd1"
                }
            }
            ]
        
### Get Stock of an item ID [GET /{id}]

+ Parameters

    + id (required, uuid, `ecf41802-c810-11e8-a8d5-f2801f1b9fd1`) ... Item ID (`id`)

+ Response 200 (application/vnd.api+json)

            + Headers
     connection: close
     content-type: application/json;charset=UTF-8
     date: Thu, 04 Oct 2018 22:06:09 GMT
     
    + Body
    
    
            {
                "quantity": 20,
                "item": {
                 "name": "Bread",
                 "price": 1.2,
                 "id": "ecf41802-c810-11e8-a8d5-f2801f1b9fd1"
              }
            }